name: Vue.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout source
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'   # Vue CLI 5 works well with Node 16 or 18

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run lint (skip gracefully if no lint script)
      - name: Run lint
        run: npm run lint --if-present

      # Run build (Vue CLI build)
      - name: Build project
        run: npm run build
